# -*- coding: utf-8 -*-
{
    "name": "Approval on payments",
    "version": "18.0.1.0.0",
    "category": "Tools",
    "summary": "Patch to fix the name of incoming invoices",
    "description": "This is an autogenerated module scaffold.",
    "author": 'GonzaOdoo',
    "maintainer": "GonzaOdoo",
    "website": 'https://www.yourcompany.com',
    "depends": ['account'],
    "data":[
        'views/views.xml',
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}